### ISSUE TITLE
phaes vs funiq

### ISSUE THREAD

**Issue by spawn-guy** [spinen/laravel-geometry#32]
I am researching geo-related packages for my work and i see that original library https://github.com/phayes/geoPHP was not updated for quite some time (5 years).

there is an active commentator that, apparently, maintains this fork https://github.com/funiq/geoPHP

is it possible to switch to use this newer fork with laravel?

**Comment by jimmypuckett** [comment]
@spawn-guy Do you know if there is any docs on "upgrading" to the newer fork that specifys any known issues?  I could not find any on their site.

Do you know what the new fork adds or problems that it solves?

/cc @ssfinney

**Comment by spawn-guy** [comment]
It looks like a drop-in replacement with no breaking things.

Looking at commit hisrory: they are fixing bugs, refactoring and Rewriting parts, cleaning code, adding missing Geos methods. And supporting php7

**Comment by jimmypuckett** [comment]
@spawn-guy I started this branch to test this & there are a few things...

1. They only have a `dev-master` tag for `funiq/geoPHP`, so that leaves us open to things being broken very easy with their future updates, so may wait until https://github.com/funiq/geoPHP/issues/2 is addressed

2. This is *NOT* a drop in replacement.  They have namespaced all of the classes, so we will need to address the namespace.  I have always disliked that geoPHP was in the root, so this is a good thing, but also a breaking thing, so just need to think through it.

We actually don't have a project that uses this library anymore, so I have no way to test the code outside of our automated tests, so we will need help with someone actually using it in an application.

**Comment by BathoryPeter** [comment]
Hi!
I'm the developer of funiq/geoPHP. After a longer inactive period I released v2.0 a few weeks ago and now working on v2.1. Please let me know if you have any question, idea or feature request.

**Comment by jimmypuckett** [comment]
Going to close this as it is inactive.  Please reopen if needed.
